image: 'rust:latest'

stages:
  - build
  - test

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

build:
  stage: build
  script:
    - cargo build
  cache:
    paths:
      - cargo/
      - target/

test:
  stage: test
  dependencies:
    - build
  script:
    - cargo test
