[package]
name = "orbtk-shell"
version = "0.1.0"
authors = ["Florian Blasius <flovanpt@posteo.de>"]
description = "Window shell crate used by OrbTk."
repository = "https://gitlab.redox-os.org/redox-os/orbtk"
license = "MIT"
keywords = ["shell", "window", "ui"]
edition = "2018"

[target.wasm32-unknown-unknown.dependencies]
stdweb = "0.4.17"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
gl = { version = "0.6", optional = true }
glutin = { version = "0.21.0", optional = true }
orbfont = { git = "https://gitlab.redox-os.org/redox-os/orbfont.git", optional = true }
orbclient = { version = "0.3.22", optional = true }

[dependencies]
orbtk-render = { version = "0.1.0", path = "../render" }
orbtk-utils = { version = "0.1.0", path = "../utils" }
lazy_static = "1.3.0"

[features]
default = ["orbfont", "orbclient"]
preview = ["glutin", "gl"]