[package]
name = "orbtk-render"
version = "0.1.0"
authors = ["Florian Blasius <flovanpt@posteo.de>"]
description = "2D Render library use by OrbTk."
repository = "https://gitlab.redox-os.org/redox-os/orbtk"
license = "MIT"
keywords = ["2D", "render", "canvas"]
edition = "2018"

[target.wasm32-unknown-unknown.dependencies]
stdweb = "0.4.17"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
orbclient = { version = "0.3.22", optional = true }
orbfont = { git = "https://gitlab.redox-os.org/redox-os/orbfont.git", optional = true }
orbgl = { git = "https://gitlab.redox-os.org/redox-os/orbgl.git", optional = true }
pathfinder_canvas = { git = "https://github.com/servo/pathfinder.git", optional = true }
pathfinder_geometry = { git = "https://github.com/servo/pathfinder.git", optional = true }
pathfinder_gl = { git = "https://github.com/servo/pathfinder.git", optional = true }
pathfinder_gpu = { git = "https://github.com/servo/pathfinder.git", optional = true }
pathfinder_renderer = { git = "https://github.com/servo/pathfinder.git", optional = true }
pathfinder_content = { git = "https://github.com/servo/pathfinder.git", optional = true }
skribo = { git = "https://github.com/linebender/skribo.git", optional = true }

[dependencies]
orbtk-utils = { version = "0.1.0", path = "../utils" }
orbgl_api = { git = "https://gitlab.redox-os.org/redox-os/orbgl.git", optional = true }

[features]
default = ["orbgl_api", "orbgl", "orbclient", "orbfont"]
preview = ["pathfinder_canvas", "pathfinder_geometry", "pathfinder_gl", "pathfinder_gpu", "pathfinder_renderer", "pathfinder_content", "skribo"]