name: Publish

on: [release]

jobs:
  publish: 
    name: Publish on crates.io
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v1
    - name: Login
      run: cargo login ${{ secrets.CRATES_TOKEN }} --verbose
    - name: Test
      run: cargo publish --dry-run --verbose
    - name: Publish
      run: cargo publish --verbose
      
