name: Rust

on: [push]

jobs:
  build_ubuntu:
    name: Build and test on macOS
    runs-on: macOS-latest

  steps:
  - uses: actions/checkout@v1
  - name: Install cargo
    run: brew install rust
  - name: Build
    run: cargo build --verbose
  - name: Runj tests
    run: cargo test --verbose
