name: Build and test

on: [push]

jobs:
  build: 
    name: Build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ubuntu-latest, windows-latest]
      
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      
  build_macos:
    name: Build and test on macOS
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install rust
      run: brew install rust
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
